// <auto-generated />
namespace SchoolAdmin.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedenrollmenttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedenrollmenttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201801152107480_added enrollment table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
