// <auto-generated />
namespace SchoolAdmin.Frontend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dummy_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dummy_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201711302225321_dummy_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
