// <auto-generated />
namespace SchoolAdmin.Frontend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_credit_hours_for_grades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_credit_hours_for_grades));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081629020_added_credit_hours_for_grades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
